# Generated by Django 3.2.3 on 2021-06-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_forfait'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeForfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='forfait',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='forfait',
            name='forfait',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.typeforfait'),
            preserve_default=False,
        ),
    ]
