# Generated by Django 3.2.3 on 2021-06-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210607_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forfait',
            name='name',
        ),
    ]
