# Generated by Django 3.2.3 on 2021-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_forfait_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='signal',
            field=models.BooleanField(default=False),
        ),
    ]
