# Generated by Django 3.2.3 on 2021-06-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_user_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='forfait',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
