# Generated by Django 3.2.3 on 2021-06-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_forfait_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forfait',
            name='status',
        ),
    ]
