# Generated by Django 3.2.3 on 2021-06-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_forfait_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forfait',
            old_name='forfait',
            new_name='name',
        ),
    ]
