# Generated by Django 3.2.3 on 2021-06-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_rename_forfait_forfait_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default='2020-04-06'),
            preserve_default=False,
        ),
    ]
